---
# tasks file for configure-git

- name: Configure user email
  git_config:
    name: user.email
    scope: global 
    state: present 
    value: "{{ git_user_email }}"

- name: Configure user name
  git_config:
    name: user.name
    scope: global
    state: present
    value: "{{ git_user_name }}"

- name: Configure Credential Storage
  git_config:
    name: credential.helper
    scope: global
    state: present
    value: store