---
- name: Prepare Fedora laptop
  hosts: all
  become: true

  roles:
    - update-laptop
    - configure-auto-update-security
    - install-flatpak-repo
    - install-hashicorp-repo
    - install-rpmfusion
    - install-docker
    - install-kvm
    - install-aws-api
    - install-terraform
    - install-obsidian
    - install-vscode
    - install-godot
    - install-blender
    - install-steam