---
# tasks file for install-kvm
- name: Install KVM
  dnf:
    name: '@virtualization'
    update_cache: yes
    state: latest

- name: Enable libvirtd
  systemd:
    name: libvirtd
    enabled: yes
  notify: reload-libvirtd-service