---
# tasks file for install-aws-api
- name: Download AWS CLI
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    force: true

- name: Unzip AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/

- name: Install AWS CLI
  command:
    cmd: /tmp/aws/install
  become: True