---
# tasks file for install-docker
- name: add docker repo
  get_url:
    url: '{{ docker_mirror }}/fedora/docker-ce.repo'
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  dnf:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes
    state: latest

- name: Enable Docker Daemon
  systemd:
    name: docker
    enable: yes
    notify: reload-docker-daemon